routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Route::group(['prefix' => 'dashboard', 'as' => 'admin.dashboard.','middleware' => ['dashboard']], function() {
    Route::get('/', 'DashboardController@index')->name('index');

    /**
     *  PRODUCTS
     */
    Route::get('/products', 'DashboardController@products')->name('products');
    Route::post('/products', 'DashboardController@products')->name('products');

    Route::get('/products/create', 'DashboardController@createProduct')->name('products.create');
    Route::post('/products/store', 'DashboardController@storeProduct')->name('products.store');

    Route::get('/products/{product}', 'DashboardController@editProduct')->name('products.edit');
    Route::put('/products/{product}', 'DashboardController@updateProduct')->name('products.update');

    Route::delete('/products/{product}', 'DashboardController@destroyProduct')->name('products.destroy');

    /**
     *  CATEGORIES
     */
    Route::get('/categories', 'DashboardController@categories')->name('categories')->middleware("isAdmin");
    Route::post('/categories/search', 'DashboardController@searchCategory')->name('categories.search')->middleware("isAdmin");

    Route::get('/categories/create', 'DashboardController@createCategory')->name('categories.create')->middleware("isAdmin");
    Route::post('/categories/store', 'DashboardController@storeCategory')->name('categories.store')->middleware("isAdmin");

    Route::get('/categories/{category}', 'DashboardController@editCategory')->name('categories.edit')->middleware("isAdmin");
    Route::put('/categories/{category}', 'DashboardController@updateCategory')->name('categories.update')->middleware("isAdmin");

    Route::delete('/categories/{category}', 'DashboardController@destroyCategory')->name('categories.destroy')->middleware("isAdmin");

    /**
     *  ROLES
     */
    Route::get('/roles', 'DashboardController@roles')->name('roles')->middleware("isAdmin");
    Route::post('/roles', 'DashboardController@roles')->name('roles')->middleware("isAdmin");

    Route::get('/roles/create', 'DashboardController@createRole')->name('roles.create')->middleware("isAdmin");
    Route::post('/roles/store', 'DashboardController@storeRole')->name('roles.store')->middleware("isAdmin");

    Route::get('/roles/{role}', 'DashboardController@editRole')->name('roles.edit')->middleware("isAdmin");
    Route::put('/roles/{role}', 'DashboardController@updateRole')->name('roles.update')->middleware("isAdmin");

    Route::delete('/roles/{role}', 'DashboardController@destroyRole')->name('roles.destroy')->middleware("isAdmin");


    /**
     *  USERS
     */
    
    Route::get('/users', 'DashboardController@users')->name('users');
    Route::post('/users', 'DashboardController@users')->name('users');

    Route::get('/users/create', 'DashboardController@createUser')->name('users.create')->middleware("isAdmin");
    Route::post('/users/store', 'DashboardController@storeUser')->name('users.store')->middleware("isAdmin");

    Route::get('/users/{user}', 'DashboardController@editUser')->name('users.edit');
    Route::put('/users/{user}', 'DashboardController@updateUser')->name('users.update');

    Route::get('/users/view/{user}', 'DashboardController@showUser')->name('users.show');

    Route::delete('/users/{user}', 'DashboardController@destroyUser')->name('users.destroy');
	Route::get('/users/permissions/{user}', 'DashboardController@permissions')->name('users.permissions')->middleware("isAdmin");
    
    Route::put('/users/permissions/{user}', 'DashboardController@updatePermissionsUser')->name('users.permissions.update')->middleware("isAdmin");

    Route::get('/users/orders/{invoice}', 'DashboardController@showInvoice')->name('users.orders.show');

    /**
     *  SELLERS
     */

    Route::get('/sellers', 'DashboardController@sellers')->name('sellers')->middleware("isAdmin");
    Route::post('/sellers', 'DashboardController@sellers')->name('sellers')->middleware("isAdmin");

    Route::get('/sellers/create', 'DashboardController@createSeller')->name('sellers.create')->middleware("isAdmin");
    Route::post('/sellers/store', 'DashboardController@storeSeller')->name('sellers.store')->middleware("isAdmin");

    Route::get('/sellers/{user}', 'DashboardController@editSeller')->name('sellers.edit')->middleware("isAdmin");
    Route::put('/sellers/{user}', 'DashboardController@updateSeller')->name('sellers.update')->middleware("isAdmin");

    Route::get('/sellers/view/{user}', 'DashboardController@showSeller')->name('sellers.show')->middleware("isAdmin");

    Route::delete('/sellers/{user}', 'DashboardController@destroySeller')->name('sellers.destroy')->middleware("isAdmin");
	Route::get('/sellers/permissions/{user}', 'DashboardController@permissions')->name('sellers.permissions')->middleware("isAdmin");
    
    Route::put('/sellers/permissions/{user}', 'DashboardController@updatePermissionsUser')->name('sellers.permissions.update')->middleware("isAdmin");

    /**
     *  PROVIDERS
     */

    Route::get('/providers', 'DashboardController@providers')->name('providers')->middleware("isAdmin");
    Route::post('/providers', 'DashboardController@providers')->name('providers')->middleware("isAdmin");

    Route::get('/providers/create', 'DashboardController@createProvider')->name('providers.create')->middleware("isAdmin");
    Route::post('/providers/store', 'DashboardController@storeProvider')->name('providers.store')->middleware("isAdmin");

    Route::get('/providers/{user}', 'DashboardController@editProvider')->name('providers.edit')->middleware("isAdmin");
    Route::put('/providers/{user}', 'DashboardController@updateProvider')->name('providers.update')->middleware("isAdmin");

    Route::get('/providers/view/{user}', 'DashboardController@showProvider')->name('providers.show')->middleware("isAdmin");

    Route::delete('/providers/{user}', 'DashboardController@destroyProvider')->name('providers.destroy')->middleware("isAdmin");
	Route::get('/providers/permissions/{user}', 'DashboardController@permissions')->name('providers.permissions')->middleware("isAdmin");
    
    Route::put('/providers/permissions/{user}', 'DashboardController@updatePermissionsUser')->name('providers.permissions.update')->middleware("isAdmin");


    /**
     *  ADMIN PROFILE
     */

    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::post('/profile/user/{user}', 'DashboardController@updateProfile')->name('profile.user.update');

    /**
     * CONFIG
     */

    Route::get('/settings', 'DashboardController@settings')->name('settings');
    Route::post('/settings', 'DashboardController@storeSettings')->name('settings.store');

    /**
     * ORDERS
     */
    
    Route::get('/orders', 'DashboardController@orders')->name('orders');
    Route::post('/orders', 'DashboardController@orders')->name('orders');
    Route::get('/orders/{order}', 'DashboardController@showOrder')->name('orders.show');
    Route::get('/orders/{order}/download_invoice', 'DashboardController@downloadInvoice')->name('orders.download_invoice');

    /**
     * CONTENTS
     */

    Route::get('/contents', 'DashboardController@contents')->name('contents')->middleware("isAdmin");
    
    Route::get('/contents/create', 'DashboardController@createContent')->name('contents.create')->middleware("isAdmin");
    Route::post('/contents/store', 'DashboardController@storeContent')->name('contents.store')->middleware("isAdmin");
    
    Route::get('/contents/{content}', 'DashboardController@editContent')->name('contents.edit')->middleware("isAdmin");
    Route::put('/contents/{content}', 'DashboardController@updateContent')->name('contents.update')->middleware("isAdmin");

    Route::delete('/contents/{content}', 'DashboardController@destroyContent')->name('contents.destroy')->middleware("isAdmin");

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');

//Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/verify', 'Auth\RegisterController@verifyUser')->name('verify.user');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');


Route::post(
    'stripe/webhook',
    'StripeWebHookController@handleWebhook'
);

Route::group(['prefix' => 'web', 'as' => 'web.'], function() {
    Route::get('/{module}/{cat}', 'HomeController@products')->name('products');
    Route::get('/{module}/{cat}/{product}', 'HomeController@showProduct')->name('products.show');
});

/**
 * CUSTOMER ROUTES
 */

Route::group(['prefix' => 'customer', 'as' => 'customer.', 'middleware' => ['auth', 'verified']], function () {
    Route::get('/profile', 'CustomerController@profile')->name('profile');
    Route::put('/profile', 'CustomerController@updateProfile')->name('profile.update');
    Route::put('/password', 'CustomerController@updatePassword')->name('password.update');

    
    Route::get('directions/json', 'CustomerController@json')->name('directions.json');
    Route::post('directions', 'CustomerController@store')->name('directions.store');
    Route::delete('directions/destroy', 'CustomerController@destroyDirection')->name('directions.destroy');
    Route::put('directions/update', 'CustomerController@updateDirection')->name('directions.update');
    //Route::post('/directions', 'CustomerController@createDirection')->name('directions.create');
    //Route::put('/directions/{direction}', 'CustomerController@updateDirection')->name('directions.update');
    //Route::delete('/directions/{direction}', 'CustomerController@destroyDirection')->name('directions.destroy');

    Route::post('/shipping', 'CustomerController@shippingDirection')->name('directions.shipping');
    Route::get('/get-shipping', 'CustomerController@shippingDirection')->name('directions.get_shipping');

    Route::post("credit-card", 'BillingController@processCreditCardForm')
        ->name("billing.process_credit_card");

    Route::get('/products', 'CustomerController@products')
        ->name('products');

    Route::get('orders/json', 'CustomerController@jsonOrders')->name('orders.json');
    Route::get('/orders', 'CustomerController@orders')->name('orders');
    Route::get('/orders/{order}', 'CustomerController@showOrder')->name('orders.show');
    Route::get('/orders/{order}/download_invoice', 'CustomerController@downloadInvoice')->name('orders.download_invoice');
   
});

Route::get('/', 'HomeController@index')->name('home');

Route::get('/products', 'HomeController@products')->name('products');

 Route::get('customer/order/download', 'CustomerController@downloadInvoiceId')->name('orders.invoice');
/**
 * CART ROUTES
 */
Route::post('/add-product-to-cart/{product}', 'CustomerController@addProductToCart')
    ->name('add_product_to_cart');
Route::get('/cart', 'CustomerController@showCart')
    ->name('cart');
Route::get('/remove-product-from-cart/{product}', 'CustomerController@removeProductFromCart')
    ->name('remove_product_from_cart');
Route::post('/change-quantity-product/{product}', 'CustomerController@changeQuantityProduct')
    ->name('change_quantity_product');


Route::group(["middleware" => ["auth"]], function () {
    Route::get('/checkout', 'CheckoutController@index')
        ->name('checkout_form');
    Route::post('/checkout', 'CheckoutController@processOrder')
        ->name('process_checkout');
});

/**
* Comprobar redsys
*/
Route::post('/redsys/notification','RedsysController@comprobar');
Route::get('/redsys/notification','RedsysController@comprobar');

Route::post('miJqueryAjax','CustomerController@shippingDirection');

app/Models/Content.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Hashidable;
use Illuminate\Database\Eloquent\SoftDeletes;
/**
 * App\Models\Content
 *
 * @property int $id
 * @property int $user_id
 * @property string $title
 * @property string $content
 * @property string|null $deleted_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|Content newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Content newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Content query()
 * @method static \Illuminate\Database\Eloquent\Builder|Content whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Content whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Content whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Content whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Content whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Content whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Content whereUserId($value)
 * @mixin \Eloquent
 */
class Content extends Model
{
    use Hashidable, SoftDeletes;
     protected $fillable = [
        'title', 'content'
    ];
    protected static function boot() {
        parent::boot();
        if ( !app()->runningInConsole()) {
            self::saving(function ($table) {
                $table->user_id = auth()->id();
            });
        }
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public static function getContents(){
        return Content::get();
    }
}

resources/views/web/content/products/index.blade.php
@extends("layouts.web")


@section("content")
    @include("web.content.products.list")
@endsection


@push('js')
    
    <script>
        $(document).ready(function(){
            // Target your element
            $('#content').colourBrightness();
            if($('#content').hasClass("light")){
                $('.logo').attr('src', "{{ url('/storage/web/logonegro.png') }}" );
            }

            if($('#content').hasClass("dark")){
                $('.logo').attr('src', "{{ url('/storage/web/logoblanco.png') }}" );
            }
            function hover(element) {
                element.setAttribute('src', '/storage/web/carrito-n.svg');
            }
        });
    </script>
    
@endpush

resources/views/web/content/products/list.blade.php
@extends("layouts.web")

@push('css')
   <style>
       .wrapper-product{
           width: 430px;
       }
       .product-container {
            background-color: #fff;
            height: 450px;
            overflow: hidden;
            position: relative;
            margin-bottom: 20px;
            border-radius: 50%;
            width: 400px;
        }

        .tag-featured, .tag-discount {
            background-color: red;
            width: 50px;
            height: 70px;
            position: absolute;
            color: #fff;
            right: 40px;
            z-index: 9;
            top: 35px;
            transform: rotate(137deg);
            border-radius: 0 50%;
        }

        .tag-featured::before, .tag-discount::before {
            color: #fff;
            font-weight: bold;
            display: block;
            transform-origin: top center;
            transform: rotate(222.5deg) translateX(-28px) translateY(-37px);
        }

        .tag-discount::before{
            content: attr(data-before);
        }
        

        .product-description {
            padding: 10px 20px;
            color: #797979;
        }

        .product-image {
            /*padding: 20px;*/
            height: 323px;
            position: relative;
            overflow: hidden;
            transition: 1s;
        }

        .product-link {
            position: absolute;
            background: #fff;
            width: 100px;
            height: 100px;
            color: #4E5156;            
            border-radius: 50%;
            font-size: 25px;
            text-align: center;
            padding: 35px 0;
            line-height: 25px;
            left: calc(50% - 50px);
            top: calc(50% - 50px);
            opacity: 0;
            transition: 1s;
            font-style: italic;
        }

        .product-link:hover {
            text-decoration: none;
            color: rgba(0,0,0,0.36);
        }


        .hover-link {
            background-color: rgba(0,0,0,0.36);
            position: absolute;
            left: 0;
            top: 0;
            opacity: 0;
            width: 100%;
            height: 100%;
            transition: 0.5s;
        }

        .product-image img {
            width: 100%;
        }

        .product-description h1 {
            font-size: 23px;
            margin-bottom: 5px;
            margin-top: 0;
            text-align: center;
            width: 100%;
        }

        .product-description p {
            color: #C4C4C4;
        }

        .product-description .price {
            width: 100%;
            font-size: 23px;
            text-align: center;
            font-weight: bold;
            color: #000;
            margin-bottom: 5px;
        }

        .description{
            overflow: hidden;
            text-overflow: ellipsis;
            display: -webkit-box;
            -webkit-line-clamp: 2; /* number of lines to show */
            -webkit-box-orient: vertical;
            margin-top: -10px;
        }

        .product-cart {
            display: none;
        }

     
        .product-container:hover {
            box-shadow: 0px 10px 25px -2px rgba(0,0,0,0.36);
        }

        .product-container:hover .product-image {
            transition: 1s;
            /*padding: 10px;*/
        }

        .product-container:hover .product-cart {
            display: block;
            position: absolute;
            
           
            width: 300px;
           
            padding: 5px;
            display: flex;
            justify-content: center;
            align-items: center;
            
            /* position the div in center */
            position: absolute;
            top: 75%;
            left: 50%;
            transform: translate(-50%, -50%);
        
            
        }
        .product-container:hover .hover-link {
            opacity: 0.5;
        }
        .product-container:hover .product-link {
            opacity: 1;
        }

        .product-link:hover {
            -webkit-animation: hovering 1000ms linear both;
            animation: hovering 1000ms linear both;
        }
        
    </style>
@endpush

@section('title', __($category->name) )

@section('page')
    
    <h1 class="title-page text-md-left text-sm-center"> {{ $category->name }} </h1>

@endsection

@include('partials.video', ['category' => $category])

@section('content')
 
        <div class="container wrapper-container">
            <div class="row">
                @forelse($category->productsCustomer as $product)
                    <div class="col-md-4 d-flex flex-wrap wrapper-product">
                        <div class="product-container">
                            @if($product->featured)
                                <div class="tag-featured"></div>
                            @endif
                            
                          
                            <div class="product-image">
                                @if($product->in_discount)
                                    <div class="tag-discount" data-before="{{ $product->discount_type == \App\Models\Product::PERCENT ? '-'. $product->discount . '%' : '-'. $product->discount . '€' }}"></div>
                                @endif
                                <span class="hover-link"></span>
                                <a href="{{ route('web.products.show', [ 'module' => $category->module_name , 'cat' =>  $category->slug, 'product' => $product ] )}}" class="product-link">{{ __('Más') }}</a>
                                <img class="img-responsive" src="{{ $product->imagePath() }}" alt="{{ $product->name }}">
                            </div>
                            <div class="product-description">
                                <div class="product-label">
                                    <div class="product-name">
                                        <h1>{{ $product->name }}</h1>
                                        @if($product->in_discount)
                                            <p class="price"><del><small>{{ $product->formatted_price }}</small></del><br/> {{ $product->priceWithDiscount() }}</p>
                                        @else
                                            <p class="price"> {{ $product->formatted_price }} </p>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="product-cart">
                                <div class="col d-flex justify-content-center">
                                    {!! Form::model($product, ['route' => ['add_product_to_cart', ["product" => $product]], 'files' => true]) !!}
                                        
                                    <div class="input-group mb-3">
                                        {!! Form::number('qty', "1" , ['min' => '0', 'max' => $product->stock, 'step' => '1' ]) !!}
                                        
                
                                        {!! Form::submit( __('AÑADIR AL CARRITO'), ['class' => 'btn btn-cart mx-1']); !!}
                                        
                                    </div>
                                    {!! Form::close() !!}

                                        
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                
                @empty

                @endforelse
                
            </div>
        </div>
  
@endsection


@push('js')
    
    <script>
        $(document).ready(function(){
            // Target your element
            $('#content').colourBrightness();
            if($('#content').hasClass("light")){
                $('.logo').attr('src', "{{ url('/storage/web/logonegro.png') }}" );
            }

            if($('#content').hasClass("dark")){
                $('.logo').attr('src', "{{ url('/storage/web/logoblanco.png') }}" );
            }
            function hover(element) {
                element.setAttribute('src', '/storage/web/carrito-n.svg');
            }
        });
    </script>
    
@endpush

resources/views/web/content/products/show.blade.php
@extends("layouts.web")

@push('css')
   <style>
       .product{
            overflow: hidden;
            background-color: rgba(255,255,255,0.8);
            height: 600px;
            width: 600px;
            border-radius: 50%;
            position: absolute;
            margin: auto;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
        }

        .product .row{
            margin: auto;
           
        }

        .product .content{
            height: 75%;
        }

        .product .content img{
            padding-top: 3rem; 
        }

        .product .title{
            position: absolute;
            top: 50px;
            left: 0;
            right: 0;
        }

        .product .description-wrapper{
            width: 300px;
            height: 300px;
            position: relative;
            margin: 10vh auto 0; /*OPTIONAL MARGIN*/
        }
        .product .description{
            overflow: hidden;
            width: 100%;
            height: 100%;
            position: relative;
            margin: 0;
        }
        .product .description p {
            height: 100%;
            padding: 0;
        }
        
        .product .description::before {
            content: "";
            width: 50%;
            height: 120%;
            float: right;
            shape-outside: polygon(
                2% 0%,
                100% 0%,
                100% 100%,
                2% 100%,
                50% 94%,
                79.6% 82.7%,
                90% 65.6%,
                90% 50%,
                83% 32.6%,
                68.6% 17.3%,
                50% 6%
            );
            shape-margin: 7%;
        }
        
        @media (min-width: 850px) {
        
            .description-wrapper{
                width: 370px;
                height: 370px;
            }
            .text p {
                font-size: 26px;
            }

            
        }
        
        
        @media (max-width: 650px){
            .product{
                width: 450px;
                height: 450px;
            }
            .product .content{
                height: 65%;
            }

            .product .content img{
                padding-top: inherit; 
            }

            .product .description{
                padding-top: 2rem;; 
            }
        }

        @media (max-width: 500px){
            .product{
                width: 350px;
                height: 350px;
                top: inherit;
                bottom: 75px;
            }
        }

        @media (max-width: 450px){
            .product .content img{
                margin-top: -50px; 
            }

            .product .description{
                padding-top: 0.2rem;; 
            }
        }
        @media (max-width: 320px){
            .product{
                bottom: 0px;
            }
        }

        

        @media (max-width: 1024px) and (orientation: landscape){
            
            .product{
                top: 150px;
            }
                     
        }

        @media (max-width: 950px) and (orientation: landscape){
            h3{
                font-size: 1.4rem;
            }
            .product{
                width: 300px;
                height: 300px;
                top: 50px;
            }
            .product .description-wrapper{
                width: 140px;
                height: 140px;
            }

            .product .content img {
                padding-top: 4rem;
            }

            .product .content {
                height: 70%;
            }

            .product .content .description{
                top: 30px;
            }

            
        }
        
    </style>
@endpush

@section('title', __($product->name) )

@section('page')
    
    <a href="{{ route('web.products', [ 'module' => $category->module_name , 'cat' =>  $category->slug ] )}}" class="title-page text-md-left text-sm-center text-decoration-none text-reset">
        <h1> {{ $category->name }} </h1>
    </a>

@endsection

@include('partials.video', ['category' => $category])

@section('content')
    @include('partials.web.products.show', ['show' => true ])
@endsection


@push('js')
    
    <script>
        $(document).ready(function(){
            // Target your element
            $('#content').colourBrightness();
            if($('#content').hasClass("light")){
                $('.logo').attr('src', "{{ url('/storage/web/logonegro.png') }}" );
            }

            if($('#content').hasClass("dark")){
                $('.logo').attr('src', "{{ url('/storage/web/logoblanco.png') }}" );
            }
            function hover(element) {
                element.setAttribute('src', '/storage/web/carrito-n.svg');
            }
        });
    </script>
    
@endpush