routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Route::group(['prefix' => 'dashboard', 'as' => 'admin.dashboard.','middleware' => ['dashboard']], function() {
    Route::get('/', 'DashboardController@index')->name('index');

    /**
     *  PRODUCTS
     */
    Route::get('/products', 'DashboardController@products')->name('products');
    Route::post('/products', 'DashboardController@products')->name('products');

    Route::get('/products/create', 'DashboardController@createProduct')->name('products.create');
    Route::post('/products/store', 'DashboardController@storeProduct')->name('products.store');

    Route::get('/products/{product}', 'DashboardController@editProduct')->name('products.edit');
    Route::put('/products/{product}', 'DashboardController@updateProduct')->name('products.update');

    Route::delete('/products/{product}', 'DashboardController@destroyProduct')->name('products.destroy');

    /**
     *  CATEGORIES
     */
    Route::get('/categories', 'DashboardController@categories')->name('categories')->middleware("isAdmin");
    Route::post('/categories/search', 'DashboardController@searchCategory')->name('categories.search')->middleware("isAdmin");

    Route::get('/categories/create', 'DashboardController@createCategory')->name('categories.create')->middleware("isAdmin");
    Route::post('/categories/store', 'DashboardController@storeCategory')->name('categories.store')->middleware("isAdmin");

    Route::get('/categories/{category}', 'DashboardController@editCategory')->name('categories.edit')->middleware("isAdmin");
    Route::put('/categories/{category}', 'DashboardController@updateCategory')->name('categories.update')->middleware("isAdmin");

    Route::delete('/categories/{category}', 'DashboardController@destroyCategory')->name('categories.destroy')->middleware("isAdmin");

    /**
     *  ROLES
     */
    Route::get('/roles', 'DashboardController@roles')->name('roles')->middleware("isAdmin");
    Route::post('/roles', 'DashboardController@roles')->name('roles')->middleware("isAdmin");

    Route::get('/roles/create', 'DashboardController@createRole')->name('roles.create')->middleware("isAdmin");
    Route::post('/roles/store', 'DashboardController@storeRole')->name('roles.store')->middleware("isAdmin");

    Route::get('/roles/{role}', 'DashboardController@editRole')->name('roles.edit')->middleware("isAdmin");
    Route::put('/roles/{role}', 'DashboardController@updateRole')->name('roles.update')->middleware("isAdmin");

    Route::delete('/roles/{role}', 'DashboardController@destroyRole')->name('roles.destroy')->middleware("isAdmin");


    /**
     *  USERS
     */
    
    Route::get('/users', 'DashboardController@users')->name('users');
    Route::post('/users', 'DashboardController@users')->name('users');

    Route::get('/users/create', 'DashboardController@createUser')->name('users.create')->middleware("isAdmin");
    Route::post('/users/store', 'DashboardController@storeUser')->name('users.store')->middleware("isAdmin");

    Route::get('/users/{user}', 'DashboardController@editUser')->name('users.edit');
    Route::put('/users/{user}', 'DashboardController@updateUser')->name('users.update');

    Route::get('/users/view/{user}', 'DashboardController@showUser')->name('users.show');

    Route::delete('/users/{user}', 'DashboardController@destroyUser')->name('users.destroy');
	Route::get('/users/permissions/{user}', 'DashboardController@permissions')->name('users.permissions')->middleware("isAdmin");
    
    Route::put('/users/permissions/{user}', 'DashboardController@updatePermissionsUser')->name('users.permissions.update')->middleware("isAdmin");

    Route::get('/users/orders/{invoice}', 'DashboardController@showInvoice')->name('users.orders.show');

    /**
     *  SELLERS
     */

    Route::get('/sellers', 'DashboardController@sellers')->name('sellers')->middleware("isAdmin");
    Route::post('/sellers', 'DashboardController@sellers')->name('sellers')->middleware("isAdmin");

    Route::get('/sellers/create', 'DashboardController@createSeller')->name('sellers.create')->middleware("isAdmin");
    Route::post('/sellers/store', 'DashboardController@storeSeller')->name('sellers.store')->middleware("isAdmin");

    Route::get('/sellers/{user}', 'DashboardController@editSeller')->name('sellers.edit')->middleware("isAdmin");
    Route::put('/sellers/{user}', 'DashboardController@updateSeller')->name('sellers.update')->middleware("isAdmin");

    Route::get('/sellers/view/{user}', 'DashboardController@showSeller')->name('sellers.show')->middleware("isAdmin");

    Route::delete('/sellers/{user}', 'DashboardController@destroySeller')->name('sellers.destroy')->middleware("isAdmin");
	Route::get('/sellers/permissions/{user}', 'DashboardController@permissions')->name('sellers.permissions')->middleware("isAdmin");
    
    Route::put('/sellers/permissions/{user}', 'DashboardController@updatePermissionsUser')->name('sellers.permissions.update')->middleware("isAdmin");

    /**
     *  PROVIDERS
     */

    Route::get('/providers', 'DashboardController@providers')->name('providers')->middleware("isAdmin");
    Route::post('/providers', 'DashboardController@providers')->name('providers')->middleware("isAdmin");

    Route::get('/providers/create', 'DashboardController@createProvider')->name('providers.create')->middleware("isAdmin");
    Route::post('/providers/store', 'DashboardController@storeProvider')->name('providers.store')->middleware("isAdmin");

    Route::get('/providers/{user}', 'DashboardController@editProvider')->name('providers.edit')->middleware("isAdmin");
    Route::put('/providers/{user}', 'DashboardController@updateProvider')->name('providers.update')->middleware("isAdmin");

    Route::get('/providers/view/{user}', 'DashboardController@showProvider')->name('providers.show')->middleware("isAdmin");

    Route::delete('/providers/{user}', 'DashboardController@destroyProvider')->name('providers.destroy')->middleware("isAdmin");
	Route::get('/providers/permissions/{user}', 'DashboardController@permissions')->name('providers.permissions')->middleware("isAdmin");
    
    Route::put('/providers/permissions/{user}', 'DashboardController@updatePermissionsUser')->name('providers.permissions.update')->middleware("isAdmin");


    /**
     *  ADMIN PROFILE
     */

    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::post('/profile/user/{user}', 'DashboardController@updateProfile')->name('profile.user.update');

    /**
     * CONFIG
     */

    Route::get('/settings', 'DashboardController@settings')->name('settings');
    Route::post('/settings', 'DashboardController@storeSettings')->name('settings.store');

    /**
     * ORDERS
     */
    
    Route::get('/orders', 'DashboardController@orders')->name('orders');
    Route::post('/orders', 'DashboardController@orders')->name('orders');
    Route::get('/orders/{order}', 'DashboardController@showOrder')->name('orders.show');
    Route::get('/orders/{order}/download_invoice', 'DashboardController@downloadInvoice')->name('orders.download_invoice');

    /**
     * CONTENTS
     */

    Route::get('/contents', 'DashboardController@contents')->name('contents')->middleware("isAdmin");
    
    Route::get('/contents/create', 'DashboardController@createContent')->name('contents.create')->middleware("isAdmin");
    Route::post('/contents/store', 'DashboardController@storeContent')->name('contents.store')->middleware("isAdmin");
    
    Route::get('/contents/{content}', 'DashboardController@editContent')->name('contents.edit')->middleware("isAdmin");
    Route::put('/contents/{content}', 'DashboardController@updateContent')->name('contents.update')->middleware("isAdmin");

    Route::delete('/contents/{content}', 'DashboardController@destroyContent')->name('contents.destroy')->middleware("isAdmin");

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');

//Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/verify', 'Auth\RegisterController@verifyUser')->name('verify.user');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');


Route::post(
    'stripe/webhook',
    'StripeWebHookController@handleWebhook'
);

Route::group(['prefix' => 'web', 'as' => 'web.'], function() {
    Route::get('/{module}/{cat}', 'HomeController@products')->name('products');
    Route::get('/{module}/{cat}/{product}', 'HomeController@showProduct')->name('products.show');
});

/**
 * CUSTOMER ROUTES
 */

Route::group(['prefix' => 'customer', 'as' => 'customer.', 'middleware' => ['auth', 'verified']], function () {
    Route::get('/profile', 'CustomerController@profile')->name('profile');
    Route::put('/profile', 'CustomerController@updateProfile')->name('profile.update');
    Route::put('/password', 'CustomerController@updatePassword')->name('password.update');

    
    Route::get('directions/json', 'CustomerController@json')->name('directions.json');
    Route::post('directions', 'CustomerController@store')->name('directions.store');
    Route::delete('directions/destroy', 'CustomerController@destroyDirection')->name('directions.destroy');
    Route::put('directions/update', 'CustomerController@updateDirection')->name('directions.update');
    //Route::post('/directions', 'CustomerController@createDirection')->name('directions.create');
    //Route::put('/directions/{direction}', 'CustomerController@updateDirection')->name('directions.update');
    //Route::delete('/directions/{direction}', 'CustomerController@destroyDirection')->name('directions.destroy');

    Route::post('/shipping', 'CustomerController@shippingDirection')->name('directions.shipping');
    Route::get('/get-shipping', 'CustomerController@shippingDirection')->name('directions.get_shipping');

    Route::post("credit-card", 'BillingController@processCreditCardForm')
        ->name("billing.process_credit_card");

    Route::get('/products', 'CustomerController@products')
        ->name('products');

    Route::get('orders/json', 'CustomerController@jsonOrders')->name('orders.json');
    Route::get('/orders', 'CustomerController@orders')->name('orders');
    Route::get('/orders/{order}', 'CustomerController@showOrder')->name('orders.show');
    Route::get('/orders/{order}/download_invoice', 'CustomerController@downloadInvoice')->name('orders.download_invoice');
   
});

Route::get('/', 'HomeController@index')->name('home');

Route::get('/products', 'HomeController@products')->name('products');

 Route::get('customer/order/download', 'CustomerController@downloadInvoiceId')->name('orders.invoice');
/**
 * CART ROUTES
 */
Route::post('/add-product-to-cart/{product}', 'CustomerController@addProductToCart')
    ->name('add_product_to_cart');
Route::get('/cart', 'CustomerController@showCart')
    ->name('cart');
Route::get('/remove-product-from-cart/{product}', 'CustomerController@removeProductFromCart')
    ->name('remove_product_from_cart');
Route::post('/change-quantity-product/{product}', 'CustomerController@changeQuantityProduct')
    ->name('change_quantity_product');


Route::group(["middleware" => ["auth"]], function () {
    Route::get('/checkout', 'CheckoutController@index')
        ->name('checkout_form');
    Route::post('/checkout', 'CheckoutController@processOrder')
        ->name('process_checkout');
});

/**
* Comprobar redsys
*/
Route::post('/redsys/notification','RedsysController@comprobar');
Route::get('/redsys/notification','RedsysController@comprobar');

Route::post('miJqueryAjax','CustomerController@shippingDirection');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Traits\Dashboard\ManageRoles;
use App\Traits\Dashboard\ManageProducts;
use App\Traits\Dashboard\ManageCategories;
use App\Traits\Dashboard\ManageUsers;
use App\Traits\Dashboard\ManageSellers;
use App\Traits\Dashboard\ManageProviders;
use App\Traits\Dashboard\ManageOrders;
use App\Traits\Dashboard\ManagePermissions;
use App\Traits\Dashboard\ManageProfile;
use App\Traits\Dashboard\ManageSettings;
use App\Traits\Dashboard\ManageProfits;
use App\Traits\Dashboard\ManageContents;

class DashboardController extends Controller
{
    use ManageRoles, ManageProducts, ManageCategories,ManageUsers,ManageSellers,ManageProviders,ManageOrders,ManagePermissions,ManageProfile, ManageSettings, ManageProfits, ManageContents;

    public function index(){
               
        return view('dashboard.index');
    }

    
    

}

resources/views/dashboard/sellers/create.blade.php
@extends("layouts.dashboard")

<!-- breadcrumb section -->

@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.sellers') }}">
        <i class="fas fa-users"></i> {{ __('Distribuidores') }}
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.roles.create') }}">
        <i class="fas fa-user-plus"></i> {{ __("Crear distribuidor") }}
    </a>
</li>
@endsection

<!-- breadcrumb section end-->

@section("content")
	@include("dashboard.sellers.form")
@endsection

resources/views/dashboard/sellers/edit.blade.php
@extends("layouts.dashboard")

@section('title', __("Distribuidor " . $user->name) )

<!-- breadcrumb section -->

@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.sellers') }}">
        <i class="fas fa-users"></i> {{ __('Distribuidores') }}
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.sellers.edit', $user) }}">
        <i class="fas fa-user-edit"></i> {{ $user->name }} 
    </a>
</li>
@endsection

<!-- breadcrumb section end-->

@section("content")
	@include("dashboard.sellers.form")
@endsection

resources/views/dashboard/sellers/form.blade.php
@php 
	$readonly = true; 
	$disabled = 'disabled'; 
@endphp

@can('haveaccess', 'user.edit')
	@php 
		$readonly = false; 
		$disabled = '' 
	@endphp
@endcan

@can('haveaccess', 'user.update')
	@php 
		$readonly = false; 	
		$disabled = '';
	@endphp
@endcan




@include('partials.form_errors')

<div class="container-fluid">
	{!! Form::model($user, $options) !!}
		@isset($update)
			@method("PUT")
		@endisset
		@csrf
		<div class="row page_user">
			<div class="col-xl-3">
				<div class="panel shadow">
					<div class="header d-flex justify-content-between">
						<h2 class="title">
							{!! $title !!}
						</h2>
						@if($view == 'put')
							@can('haveaccess','user.destroy')
								@if ($user->status == "100")
									<a href="#" data-route="{{ route('admin.dashboard.users.destroy',  ["user" => $user])}}" class="btn btn-success locked-record">
										<i class="fas fa-user-check"></i> {{ __('Activar') }}
									</a>
								@else
									<a href="#" data-route="{{ route('admin.dashboard.users.destroy',  ["user" => $user])}}" class="btn btn-danger locked-record">
										<i class="fas fa-user-times"></i> {{ __('Bloquear') }}
									</a>
								@endif
							@endcan
						@endif
					</div>
					<div class="inside">
						<div class="mini_profile">
							
							<img src="{{ url('/storage/web/default-avatar.png') }}" class="avatar">  
						
							<div class="info">
								
									@if($view == "post")
										@include('partials.dashboard.users.form')
									@else
										@include('partials.dashboard.users.info')
									@endif
								
									
								
								
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xl-5">
				
				@if($view == "post" || $view == "put")
					
						@include('partials.dashboard.users.roles', [ 'default' => 'SELLER'])

				@else
				<div class="panel shadow">
					<div class="header">
						<h2 class="title">
							<i class="fas fa-shopping-basket"></i>  {{ __('Pedidos')}}
						</h2>
					</div>
					<div class="inside">
						@include('partials.dashboard.users.orders')
					</div>
				</div>
				
			</div>
			<div class="col-xl-4">
				
				<div class="panel shadow">
					<div class="header">
						<h2 class="title">
							<i class="far fa-address-book"></i>  {{ __('Direcciones')}}
						</h2>
					</div>
					<div class="inside">
						@include('partials.dashboard.users.directions')
					</div>
				</div>
				@endif
			</div>
			
		</div>
		@if($view == "post" || $view == "put")
			<div class="row mtop16">
				<div class="col-md-12">
					<div class="panel shadow">
						<div class="inside">
							{!! Form::submit($textButton, ['class' => 'btn btn-dark mt-2']); !!}
						</div>
					</div>
				</div>
			</div>
		@endif
	{!! Form::close() !!}	
</div>

resources/views/dashboard/sellers/index.blade.php
@extends("layouts.dashboard")

@section('title', __('Distribuidores') )

@section("content")
	@include("dashboard.sellers.list")
@endsection

resources/views/dashboard/sellers/list.blade.php
<!-- breadcrumb section -->
@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.sellers') }}">
        <i class="fas fa-users"></i> {{ __('Distribuidores') }}
    </a>
</li>
@endsection

<!-- breadcrumb section end-->

@push('css')
    <link rel="stylesheet" href="/css/jConfirm.css" />
@endpush

<!-- role section -->
<div class="container-fluid">
    <div class="panel shadow">
        <div class="header">
            <h2 class="title">
                <i class="fas fa-users"></i> {{ __('Distribuidores') }}
			</h2>
			<ul>
				@can('haveaccess','user.create')
				<li>
					<a href="{{ route('admin.dashboard.sellers.create') }}">
						<i class="fas fa-plus"></i> {{ __('Crear distribuidor') }}
					</a>
				</li>
				@endif
			<li>
				<a href="#"><i class="fas fa-filter"></i> {{ __('Filtrar') }} <i class="fas fa-chevron-down"></i></a>
				<ul class="shadow">
                    <li>
						<form action="{{ route('admin.dashboard.sellers') }}" method="POST" id="form-all" >
							@csrf
							
							{!! Form::text('search','all', ['class' => 'd-none']) !!}
							<a href = "javascript:{}" class = "nav-item nav-link" onclick = "document.getElementById('form-all').submit();" >
								<i class="fas fa-globe-americas"></i> {{ __('Todos') }}
							</a> 
						</form>
					</li>
					<li>
						<form action="{{ route('admin.dashboard.sellers') }}" method="POST" id="form-registered" >
							@csrf
							
							{!! Form::text('search','registered', ['class' => 'd-none']) !!}
							<a href = "javascript:{}" class = "nav-item nav-link" onclick = "document.getElementById('form-registered').submit();" >
								<i class="fas fa-unlink"></i> {{ __('No verificados') }}
							</a> 
						</form>
                    </li>
                    <li>
						<form action="{{ route('admin.dashboard.sellers') }}" method="POST" id="form-verified" >
							@csrf
							
							{!! Form::text('search','verified', ['class' => 'd-none']) !!}
							<a href = "javascript:{}" class = "nav-item nav-link" onclick = "document.getElementById('form-verified').submit();" >
								<i class="fas fa-user-check"></i> {{ __('Verificados') }}
							</a> 
						</form>
                    </li>
                    <li>
						<form action="{{ route('admin.dashboard.sellers') }}" method="POST" id="form-locked" >
							@csrf
							
							{!! Form::text('search','locked', ['class' => 'd-none']) !!}
							<a href = "javascript:{}" class = "nav-item nav-link" onclick = "document.getElementById('form-locked').submit();" >
								<i class="fas fa-user-lock"></i> {{ __('Bloqueados') }}
							</a> 
						</form>
					</li>
				</ul>
			</li>
			<li>
				<a href="#" class="btn-search">
					<i class="fas fa-search"></i> {{ __('Buscar') }}
				</a>
			</li>
		</ul>
		
		<div class="inside">
            <div class="form-search d-none my-4">
				{!! Form::model([], ['route' => ['admin.dashboard.sellers'], 'files' => true]) !!}
                        @csrf
				
                <div class="row">
					
					<div class="col-md-4">
						{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => __('Busqueda') ]) !!}
					</div>
					<div class="col-md-4">
						{!! Form::select('filter',  ['0' => __('Nombre'), '1' => __('Email'), '2' => __('Población'), '3' => __('Provincia'), '4' => __('País') ] , 0, ['class' => 'form-select']) !!}
					</div>
					<div class="col-md-2">
						<button type="submit" class="btn btn-dark w-100"> {{ __('Buscar') }}</button>
					</div>
				</div>

            	{!! Form::close() !!}
				
            </div>
            
            <table class="table mtop16">
                <thead>
                    <tr>
                        <td>{{ __('Nombre') }}</td>
						<td class="d-none d-xl-table-cell d-xxl-table-cell">{{ __('Dirección') }}</td>
						<td class="d-none d-xl-table-cell d-xxl-table-cell">{{ __('Población') }}</td>
						<td class="d-none d-xl-table-cell d-xxl-table-cell">{{ __('Provincia') }}</td>
						<td class="d-none d-xl-table-cell d-xxl-table-cell">{{ __('País') }}</td>
						<td>{{ __('Teléfono') }}</td>
						<td>{{ __('Email') }}</td>
							
						@admin
							<td class="d-none d-xl-table-cell d-xxl-table-cell">{{ __('Role') }}</td>
						@endadmin
                        <td class="d-none d-xl-table-cell d-xxl-table-cell">{{ __('Estado') }}</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr>
						<td class="align-middle">{{ $user->name }}</td>
						<td class="align-middle d-none d-xl-table-cell d-xxl-table-cell">
												@if(count($user->defaultDirection))
													{{ $user->defaultDirection[0]->line_1 }}
													<br>
													{{ $user->defaultDirection[0]->postal_code }}
												 @endif
						</td>
						<td class="align-middle d-none d-xl-table-cell d-xxl-table-cell">@if(count($user->defaultDirection)){{ $user->defaultDirection[0]->country }}@endif</td>
						<td class="align-middle d-none d-xl-table-cell d-xxl-table-cell">@if(count($user->defaultDirection)){{ $user->defaultDirection[0]->city }}@endif</td>
						<td class="align-middle d-none d-xl-table-cell d-xxl-table-cell">@if(count($user->defaultDirection)){{ $user->defaultDirection[0]->state }}@endif</td>
						<td class="align-middle">@if(count($user->defaultDirection)){{ $user->defaultDirection[0]->phone }}@endif</td>
						<td class="align-middle">{{ $user->email }}</td>
						
						@admin
							<td class="align-middle d-none d-xl-table-cell d-xxl-table-cell">{{ \App\Models\User::RoleTypes($user->role) }}</td>
						@endadmin
                        <td class="align-middle d-none d-xl-table-cell d-xxl-table-cell">{{ \App\Models\User::statusTypes($user->status) }}</td>
                        <td class="align-middle">
                            <div class="opts">
                                
                               
                                <a href="{{ route('admin.dashboard.sellers.edit', $user)}}" data-toggle="tooltip" data-placement="top" title="{{ __('Editar') }}">
                                    <i class="fas fa-edit" title="{{ __('Editar') }}"></i>
                                </a>
								
                                @admin
                                    <a href="{{ route('admin.dashboard.sellers.permissions', $user)}}" data-toggle="tooltip" data-placement="top" title="{{ __('Permisos de usuario') }}">
                                        <i class="fas fa-cogs" title="{{ __('Permisos de usuario') }}"></i>
                                    </a>
                                @endadmin

                                <a href="{{ route('admin.dashboard.sellers.show', $user)}}" data-toggle="tooltip" data-placement="top" title="{{ __('Ver') }}">
                                    <i class="fas fa-eye" title="{{ __('Ver') }}"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
			</table>
			<div class="d-flex justify-content-center">
				@if(count($users))
					{{ $users->links() }}
				@endif
			</div>
        </div>
	</div>
</div>

<!-- role section end -->

resources/views/dashboard/sellers/show.blade.php
@extends("layouts.dashboard")
@section('title', __('Distribuidores') )
<!-- breadcrumb section -->
@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.sellers') }}">
        <i class="fas fa-users"></i> {{ __('Distribuidores') }}
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.sellers.show', $user) }}">
        <i class="fas fa-id-card"></i> {{ $user->name }} 
    </a>
</li>
@endsection

@section("content")
	
	@include('dashboard.sellers.form')
	
@endsection