routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Route::group(['prefix' => 'dashboard', 'as' => 'admin.dashboard.','middleware' => ['dashboard']], function() {
    Route::get('/', 'DashboardController@index')->name('index');

    /**
     *  PRODUCTS
     */
    Route::get('/products', 'DashboardController@products')->name('products');
    Route::post('/products', 'DashboardController@products')->name('products');

    Route::get('/products/create', 'DashboardController@createProduct')->name('products.create');
    Route::post('/products/store', 'DashboardController@storeProduct')->name('products.store');

    Route::get('/products/{product}', 'DashboardController@editProduct')->name('products.edit');
    Route::put('/products/{product}', 'DashboardController@updateProduct')->name('products.update');

    Route::delete('/products/{product}', 'DashboardController@destroyProduct')->name('products.destroy');

    /**
     *  CATEGORIES
     */
    Route::get('/categories', 'DashboardController@categories')->name('categories')->middleware("isAdmin");
    Route::post('/categories/search', 'DashboardController@searchCategory')->name('categories.search')->middleware("isAdmin");

    Route::get('/categories/create', 'DashboardController@createCategory')->name('categories.create')->middleware("isAdmin");
    Route::post('/categories/store', 'DashboardController@storeCategory')->name('categories.store')->middleware("isAdmin");

    Route::get('/categories/{category}', 'DashboardController@editCategory')->name('categories.edit')->middleware("isAdmin");
    Route::put('/categories/{category}', 'DashboardController@updateCategory')->name('categories.update')->middleware("isAdmin");

    Route::delete('/categories/{category}', 'DashboardController@destroyCategory')->name('categories.destroy')->middleware("isAdmin");

    /**
     *  ROLES
     */
    Route::get('/roles', 'DashboardController@roles')->name('roles')->middleware("isAdmin");
    Route::post('/roles', 'DashboardController@roles')->name('roles')->middleware("isAdmin");

    Route::get('/roles/create', 'DashboardController@createRole')->name('roles.create')->middleware("isAdmin");
    Route::post('/roles/store', 'DashboardController@storeRole')->name('roles.store')->middleware("isAdmin");

    Route::get('/roles/{role}', 'DashboardController@editRole')->name('roles.edit')->middleware("isAdmin");
    Route::put('/roles/{role}', 'DashboardController@updateRole')->name('roles.update')->middleware("isAdmin");

    Route::delete('/roles/{role}', 'DashboardController@destroyRole')->name('roles.destroy')->middleware("isAdmin");


    /**
     *  USERS
     */
    
    Route::get('/users', 'DashboardController@users')->name('users');
    Route::post('/users', 'DashboardController@users')->name('users');

    Route::get('/users/create', 'DashboardController@createUser')->name('users.create')->middleware("isAdmin");
    Route::post('/users/store', 'DashboardController@storeUser')->name('users.store')->middleware("isAdmin");

    Route::get('/users/{user}', 'DashboardController@editUser')->name('users.edit');
    Route::put('/users/{user}', 'DashboardController@updateUser')->name('users.update');

    Route::get('/users/view/{user}', 'DashboardController@showUser')->name('users.show');

    Route::delete('/users/{user}', 'DashboardController@destroyUser')->name('users.destroy');
	Route::get('/users/permissions/{user}', 'DashboardController@permissions')->name('users.permissions')->middleware("isAdmin");
    
    Route::put('/users/permissions/{user}', 'DashboardController@updatePermissionsUser')->name('users.permissions.update')->middleware("isAdmin");

    Route::get('/users/orders/{invoice}', 'DashboardController@showInvoice')->name('users.orders.show');

    /**
     *  SELLERS
     */

    Route::get('/sellers', 'DashboardController@sellers')->name('sellers')->middleware("isAdmin");
    Route::post('/sellers', 'DashboardController@sellers')->name('sellers')->middleware("isAdmin");

    Route::get('/sellers/create', 'DashboardController@createSeller')->name('sellers.create')->middleware("isAdmin");
    Route::post('/sellers/store', 'DashboardController@storeSeller')->name('sellers.store')->middleware("isAdmin");

    Route::get('/sellers/{user}', 'DashboardController@editSeller')->name('sellers.edit')->middleware("isAdmin");
    Route::put('/sellers/{user}', 'DashboardController@updateSeller')->name('sellers.update')->middleware("isAdmin");

    Route::get('/sellers/view/{user}', 'DashboardController@showSeller')->name('sellers.show')->middleware("isAdmin");

    Route::delete('/sellers/{user}', 'DashboardController@destroySeller')->name('sellers.destroy')->middleware("isAdmin");
	Route::get('/sellers/permissions/{user}', 'DashboardController@permissions')->name('sellers.permissions')->middleware("isAdmin");
    
    Route::put('/sellers/permissions/{user}', 'DashboardController@updatePermissionsUser')->name('sellers.permissions.update')->middleware("isAdmin");

    /**
     *  PROVIDERS
     */

    Route::get('/providers', 'DashboardController@providers')->name('providers')->middleware("isAdmin");
    Route::post('/providers', 'DashboardController@providers')->name('providers')->middleware("isAdmin");

    Route::get('/providers/create', 'DashboardController@createProvider')->name('providers.create')->middleware("isAdmin");
    Route::post('/providers/store', 'DashboardController@storeProvider')->name('providers.store')->middleware("isAdmin");

    Route::get('/providers/{user}', 'DashboardController@editProvider')->name('providers.edit')->middleware("isAdmin");
    Route::put('/providers/{user}', 'DashboardController@updateProvider')->name('providers.update')->middleware("isAdmin");

    Route::get('/providers/view/{user}', 'DashboardController@showProvider')->name('providers.show')->middleware("isAdmin");

    Route::delete('/providers/{user}', 'DashboardController@destroyProvider')->name('providers.destroy')->middleware("isAdmin");
	Route::get('/providers/permissions/{user}', 'DashboardController@permissions')->name('providers.permissions')->middleware("isAdmin");
    
    Route::put('/providers/permissions/{user}', 'DashboardController@updatePermissionsUser')->name('providers.permissions.update')->middleware("isAdmin");


    /**
     *  ADMIN PROFILE
     */

    Route::get('/profile', 'DashboardController@profile')->name('profile');
    Route::post('/profile/user/{user}', 'DashboardController@updateProfile')->name('profile.user.update');

    /**
     * CONFIG
     */

    Route::get('/settings', 'DashboardController@settings')->name('settings');
    Route::post('/settings', 'DashboardController@storeSettings')->name('settings.store');

    /**
     * ORDERS
     */
    
    Route::get('/orders', 'DashboardController@orders')->name('orders');
    Route::post('/orders', 'DashboardController@orders')->name('orders');
    Route::get('/orders/{order}', 'DashboardController@showOrder')->name('orders.show');
    Route::get('/orders/{order}/download_invoice', 'DashboardController@downloadInvoice')->name('orders.download_invoice');

    /**
     * CONTENTS
     */

    Route::get('/contents', 'DashboardController@contents')->name('contents')->middleware("isAdmin");
    
    Route::get('/contents/create', 'DashboardController@createContent')->name('contents.create')->middleware("isAdmin");
    Route::post('/contents/store', 'DashboardController@storeContent')->name('contents.store')->middleware("isAdmin");
    
    Route::get('/contents/{content}', 'DashboardController@editContent')->name('contents.edit')->middleware("isAdmin");
    Route::put('/contents/{content}', 'DashboardController@updateContent')->name('contents.update')->middleware("isAdmin");

    Route::delete('/contents/{content}', 'DashboardController@destroyContent')->name('contents.destroy')->middleware("isAdmin");

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/welcome', function () {
    return view('welcome');
})->name('welcome');

//Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/verify', 'Auth\RegisterController@verifyUser')->name('verify.user');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');


Route::post(
    'stripe/webhook',
    'StripeWebHookController@handleWebhook'
);

Route::group(['prefix' => 'web', 'as' => 'web.'], function() {
    Route::get('/{module}/{cat}', 'HomeController@products')->name('products');
    Route::get('/{module}/{cat}/{product}', 'HomeController@showProduct')->name('products.show');
});

/**
 * CUSTOMER ROUTES
 */

Route::group(['prefix' => 'customer', 'as' => 'customer.', 'middleware' => ['auth', 'verified']], function () {
    Route::get('/profile', 'CustomerController@profile')->name('profile');
    Route::put('/profile', 'CustomerController@updateProfile')->name('profile.update');
    Route::put('/password', 'CustomerController@updatePassword')->name('password.update');

    
    Route::get('directions/json', 'CustomerController@json')->name('directions.json');
    Route::post('directions', 'CustomerController@store')->name('directions.store');
    Route::delete('directions/destroy', 'CustomerController@destroyDirection')->name('directions.destroy');
    Route::put('directions/update', 'CustomerController@updateDirection')->name('directions.update');
    //Route::post('/directions', 'CustomerController@createDirection')->name('directions.create');
    //Route::put('/directions/{direction}', 'CustomerController@updateDirection')->name('directions.update');
    //Route::delete('/directions/{direction}', 'CustomerController@destroyDirection')->name('directions.destroy');

    Route::post('/shipping', 'CustomerController@shippingDirection')->name('directions.shipping');
    Route::get('/get-shipping', 'CustomerController@shippingDirection')->name('directions.get_shipping');

    Route::post("credit-card", 'BillingController@processCreditCardForm')
        ->name("billing.process_credit_card");

    Route::get('/products', 'CustomerController@products')
        ->name('products');

    Route::get('orders/json', 'CustomerController@jsonOrders')->name('orders.json');
    Route::get('/orders', 'CustomerController@orders')->name('orders');
    Route::get('/orders/{order}', 'CustomerController@showOrder')->name('orders.show');
    Route::get('/orders/{order}/download_invoice', 'CustomerController@downloadInvoice')->name('orders.download_invoice');
   
});

Route::get('/', 'HomeController@index')->name('home');

Route::get('/products', 'HomeController@products')->name('products');

 Route::get('customer/order/download', 'CustomerController@downloadInvoiceId')->name('orders.invoice');
/**
 * CART ROUTES
 */
Route::post('/add-product-to-cart/{product}', 'CustomerController@addProductToCart')
    ->name('add_product_to_cart');
Route::get('/cart', 'CustomerController@showCart')
    ->name('cart');
Route::get('/remove-product-from-cart/{product}', 'CustomerController@removeProductFromCart')
    ->name('remove_product_from_cart');
Route::post('/change-quantity-product/{product}', 'CustomerController@changeQuantityProduct')
    ->name('change_quantity_product');


Route::group(["middleware" => ["auth"]], function () {
    Route::get('/checkout', 'CheckoutController@index')
        ->name('checkout_form');
    Route::post('/checkout', 'CheckoutController@processOrder')
        ->name('process_checkout');
});

/**
* Comprobar redsys
*/
Route::post('/redsys/notification','RedsysController@comprobar');
Route::get('/redsys/notification','RedsysController@comprobar');

Route::post('miJqueryAjax','CustomerController@shippingDirection');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\Hashidable;

/**
 * App\Models\Category
 *
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property string $background
 * @property int $module_id
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read mixed $module_name
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Product[] $products
 * @property-read int|null $products_count
 * @method static Builder|Category filtered()
 * @method static Builder|Category newModelQuery()
 * @method static Builder|Category newQuery()
 * @method static \Illuminate\Database\Query\Builder|Category onlyTrashed()
 * @method static Builder|Category query()
 * @method static Builder|Category whereBackground($value)
 * @method static Builder|Category whereCreatedAt($value)
 * @method static Builder|Category whereDeletedAt($value)
 * @method static Builder|Category whereId($value)
 * @method static Builder|Category whereModuleId($value)
 * @method static Builder|Category whereName($value)
 * @method static Builder|Category whereSlug($value)
 * @method static Builder|Category whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|Category withTrashed()
 * @method static \Illuminate\Database\Query\Builder|Category withoutTrashed()
 * @mixin \Eloquent
 */
class Category extends Model
{
    use Hashidable, SoftDeletes;

    protected $fillable = ["name", "slug", "background","background_image", "module_id"];
    
      protected $appends = [
        "module_name"
    ];

    public function products() {
        return $this->belongsToMany(Product::class);
    }

    public function productsCustomer() {
        return $this->belongsToMany(Product::class)->where('stock','>','0')
                    ->where('status', '=', Product::PUBLISHED)
                    ->orderBy('order', 'ASC');
    }

    public function backgroundPath(){
        return sprintf('%s/%s', '/storage/categories' , $this->background);
    }
    public function backgroundImagePath(){
        return sprintf('%s/%s', '/storage/categories' , $this->background_image);
    }

    public function getModuleNameAttribute() {
        return Module::getModule($this->module_id);
    }

    public function scopeFiltered(Builder $builder) {
        $builder->withCount("products");
      
        if (session()->has('search[admin.dashboard]')) {
            
            $builder->where('module_id', '=', session('search[admin.dashboard]'));
        }else{
            $builder->where('module_id', '=', 0);
        }
        return $builder->paginate();
    }

    public static function categoriesList(){
        return Category::get()->pluck('name','id');
    }

    public static function getCategory($module){
        return Category::where('module_id', $module)->get();
    }

   
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Traits\Dashboard\ManageRoles;
use App\Traits\Dashboard\ManageProducts;
use App\Traits\Dashboard\ManageCategories;
use App\Traits\Dashboard\ManageUsers;
use App\Traits\Dashboard\ManageSellers;
use App\Traits\Dashboard\ManageProviders;
use App\Traits\Dashboard\ManageOrders;
use App\Traits\Dashboard\ManagePermissions;
use App\Traits\Dashboard\ManageProfile;
use App\Traits\Dashboard\ManageSettings;
use App\Traits\Dashboard\ManageProfits;
use App\Traits\Dashboard\ManageContents;

class DashboardController extends Controller
{
    use ManageRoles, ManageProducts, ManageCategories,ManageUsers,ManageSellers,ManageProviders,ManageOrders,ManagePermissions,ManageProfile, ManageSettings, ManageProfits, ManageContents;

    public function index(){
               
        return view('dashboard.index');
    }

    
    

}

resources/views/dashboard/categories/create.blade.php
<!-- breadcrumb section -->

@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.categories') }}">
        <i class="fas fa-boxes"></i> {{ __('Categorías') }}
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.categories.create') }}">
        <i class="fas fa-box"></i> {{ __("Crear categoría") }}
    </a>
</li>
@endsection

<!-- breadcrumb section end-->

@include('dashboard.categories.form')

resources/views/dashboard/categories/edit.blade.php
@extends("layouts.dashboard")

@section('title', __("Producto") )

<!-- breadcrumb section -->

@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.categories') }}">
        <i class="fas fa-folder"></i> {{ __('Categorías') }}
    </a>
</li>
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.categories.edit', $category) }}">
        <i class="far fa-folder-open"></i> {{ __("Editar") . " " . $category->name }}
    </a>
</li>
@endsection

<!-- breadcrumb section end-->

@section("content")
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6 col-xl-5">
            <div class="panel shadow">
                <div class="header">
                    <h2 class="title">
                        <i class="fas fa-edit">
                            {{ __("Editar Categoría") }}
                        </i>
                    </h2>
                </div>
                
                <div class="inside">
                   @include('dashboard.categories.form')

                    @if($category->background)
                        <label for="icon" class="mtop16">{{ __('Vídeo fondo actual')}}</label>
                        @include("partials.dashboard.video", $category)
                    @endif

                    @if($category->background_image)
                        <label for="icon" class="mtop16">{{ __('Imagen fondo actual')}}</label>
                        @include("partials.dashboard.image", $category)
                    @endif
                </div>
                
            </div>

           

        </div>
    </div>
</div>
@endsection

resources/views/dashboard/categories/form.blade.php
<?php $readonly = true; $disabled = 'disabled' ?>

@can('haveaccess', 'category.edit')
	<?php $readonly = false; $disabled = ''?>
@endcan

@can('haveaccess', 'category.update')
	<?php $readonly = false; $disabled = ''?>
@endcan


{!! Form::model($category, $options) !!}
     @isset($update)
        @method("PUT")
    @endisset
    {!! Form::label('name', __("País")) !!}
    <div class="input-group">
        {!! Form::label('name', '<i class="far fa-keyboard"></i>', [ 'class' => 'input-group-text'], false) !!}
        {!! Form::text('name', null, ['class' => 'form-control' .($errors->has('name') ? ' is-invalid' : '') ]) !!}
    </div>
    @if ($errors->has('name'))
        <div class="{{$errors->has('name') ? 'invalid' : 'valid'}}-feedback" style="{{$errors->has('name') ? 'display:block' : ''}}">
            <strong>{{ $errors->first('name') }}</strong>
        </div>
    @endif

    {!! Form::label('module_id', __("Continente:"), ['class' => "mtop16"]) !!}
    <div class="input-group">
        {!! Form::label('module_id', '<i class="far fa-keyboard"></i>', [ 'class' => 'input-group-text'], false) !!}
        {!! Form::select('module_id', \App\Models\Module::getModules('name','id') , null,['class' => 'form-select']) !!}
    </div>

    {!! Form::label('background', __("Vídeo:"), ['class' => "mtop16"]) !!}
    <div class="input-group">
      
        {!! Form::label('background', '<i class="fas fa-film"></i>', [ 'class' => 'input-group-text'], false) !!}
        <div class="form-file ">
            {!! Form::file('background', [ $required, 'class' => 'form-file-input', 'id' => 'customFileVideo', 'accept' => "video/*" ]) !!}
            <label class="form-file-label" for="customFile">
                {!! Form::label('background', __("Selecciona un vídeo"), ['class' => "form-file-text", 'id' => 'file-label']) !!}
            </label>
        </div>
    </div>

    {!! Form::label('background_image', __("Imagen:"), ['class' => "mtop16"]) !!}
    <div class="input-group">
      
        {!! Form::label('background_image', '<i class="fas fa-image"></i>', [ 'class' => 'input-group-text'], false) !!}
        <div class="form-file ">
            {!! Form::file('background_image', [ $required, 'class' => 'form-file-input', 'id' => 'customFileImage', 'accept' => "image/*" ]) !!}
            <label class="form-file-label" for="customFile">
                {!! Form::label('background_image', __("Selecciona una imagen"), ['class' => "form-file-text", 'id' => 'file-label-image']) !!}
            </label>
        </div>
    </div>
    
    @can('haveaccess', 'category.create')
        <div class="row mtop16">
            <div class="col-md-12">
                {!! Form::submit($textButton, ['class' => 'btn btn-dark mt-2 w-100']); !!}
            </div>
        </div>
    @endcan
{!! Form::close() !!}

@push("js")
    <script>
        jQuery(document).ready(function () {
            
            $('#customFileVideo').on('change', function() {
                var video = $('#customFileVideo')[0].files[0].name;
                $('#file-label').text(video);
               
            });
            $('#customFileImage').on('change', function() {
                var video = $('#customFileImage')[0].files[0].name;
                $('#file-label-image').text(video);
               
            });
        });
    </script>
@endpush

resources/views/dashboard/categories/index.blade.php
@extends("layouts.dashboard")

@section('title', __('Categorías') )

@section("content")
    @include("dashboard.categories.list")
@endsection

resources/views/dashboard/categories/list.blade.php
<!-- category section -->
@section('title', __("Categorías") )

<!-- breadcrumb section -->
@section('breadcrumb')
<li class="breadcrumb-item">
    <a href="{{ route('admin.dashboard.categories') }}">
        <i class="fas fa-folder"></i> {{ __('Categorías') }}
    </a>
</li>
@endsection

<!-- breadcrumb section end-->

@push('css')
    <link rel="stylesheet" href="{{ asset("css/jConfirm.css") }}" />
@endpush

<!-- category section -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="panel shadow">
                <div class="header">
                    <h2 class="title">
                        <i class="fas fa-folder-plus"></i>
                            {{ __("Agregar Categoría") }}
                    </h2>
                </div>
                
                <div class="inside">
                   
                   @include('dashboard.categories.create')
                    
                    
                </div>
            </div>

        </div>
        <div class="col-md-9">
            <div class="panel shadow">
                <div class="header">
                    <h2 class="title">
                        <i class="fas fa-folder"></i> {{ __('Categorías') }}
                    </h2>
                </div>

                <div class="inside">
                    <nav class="nav nav-pills nav-fill">
                        @foreach(\App\Models\Module::getModules('name','id') as $key => $value)
                            <a href="#" data-route="{{ route('admin.dashboard.categories.search',  ["search" => $key])}}" class="nav-item nav-link search-record {{ session('search[admin.dashboard]') == $key ? 'active' : ''  }}">
                                {{ __($value) }} 
                            </a>
                        @endforeach
                    </nav>

                    
                    <table class="table">
                        @if(count($categories))
                            <thead>
                                <tr>
                                    <td width="150px">{{ __('Nombre') }}</td>
                                    <td>{{ __('Artículos') }}</td>
                                    <td width="140px"> {{ __('Acciones') }}</td>
                                </tr>
                            </thead>
                        @endif
                        <tbody>
                           
                            @forelse($categories as $category)
                            <tr>
                               <td>{{ $category->name }}</td>
                                <td>{{ __(":count", ['count' => $category->products_count]) }}</td>
                                 <td>
                                    <div class="opts">
                                       
                                        <div class="opts">
                                            @can('haveaccess','category.edit')
                                                <a href="{{ route('admin.dashboard.categories.edit',$category)}}" data-toggle="tooltip" data-placement="top" title="Editar">
                                                    <i class="fas fa-edit" title="Editar"></i>
                                                </a>
                                            @endcan
                                            @can('haveaccess','category.destroy')
                                                <a href="#" data-route="{{ route('admin.dashboard.categories.destroy',  ["category" => $category])}}" class="delete-record" data-toggle="tooltip" data-placement="top" title="Eliminar">
                                                    <i class="fas fa-trash-alt" title="Eliminar"></i>
                                                </a>
                                            @endcan
                                        </div>
                                       
                                    </div>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <div class="empty-results my-4">
                                    {!! __("No tienes ninguna categoría todavía") !!}   
                                </div>
                            </tr>
                            @endforelse  
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-center">
                        @if(count($categories))
                            {{ $categories->links() }}
                        @endif
			        </div>
                   

                </div>
            </div>
        </div>

<!-- category section end -->